# Generated by Django 6.0 on 2025-12-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reg_no',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
