# Generated by Django 6.0 on 2025-12-16 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactform_reportpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('RENTED', 'Rented')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='rent_prices',
            field=models.JSONField(blank=True, help_text="Example: {'daily': 50, 'weekly': 300}", null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='clixs/items/'),
        ),
    ]
