# Generated by Django 6.0 on 2025-12-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpost',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
