# Generated by Django 6.0 on 2025-12-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reportpost_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpost',
            name='reason',
            field=models.TextField(),
        ),
    ]
