# Generated by Django 6.0 on 2025-12-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='reg_no',
            new_name='registration_number',
        ),
    ]
