# Generated by Django 6.0 on 2026-01-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_chat_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('item', 'buyer')},
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=2000),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['buyer'], name='api_chat_buyer_i_3d0b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['item'], name='api_chat_item_id_0c3826_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat'], name='api_message_chat_id_2b3307_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='api_message_created_824429_idx'),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='seller',
        ),
    ]
