# Generated by Django 6.0 on 2026-01-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_contactform_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='item_title_snapshot',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
