# Generated by Django 6.0 on 2026-01-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_chat_item_title_snapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
