# Generated by Django 6.0 on 2026-01-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_feedback'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chat',
            name='api_chat_buyer_i_3d0b4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='api_chat_item_id_0c3826_idx',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_label',
            field=models.CharField(db_index=True, default='', editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='chat',
            name='item_title_snapshot',
        ),
    ]
